Error, SDS and SSP updates
nhsd-a2si/docs-uec-appts pull request #370
Opened 2021-01-04 14:25 UTC by RichardTheWard

https://nhsd-jira.digital.nhs.uk/browse/ABNS-2118
https://nhsd-jira.digital.nhs.uk/browse/UECABS-13

Changes can be seen here 
https://rw-dev-branch.uec-appts.docs.opennhs.io/er_overview.html
https://rw-dev-branch.uec-appts.docs.opennhs.io/er_errorhandling.html

https://rw-dev-branch.uec-appts.docs.opennhs.io/fs_sds.html
https://rw-dev-branch.uec-appts.docs.opennhs.io/fs_ssp.html

2021-01-04 17:32 UTC, cda69 commented on _pages/functional_spec/error/er_errorhandling.md
> +If the event of an error response HTTP `4xx` or `5xx` an [OperationOutcome](https://www.hl7.org/fhir/STU3/operationoutcome.html) MUST be returned.
'In...' rather than 'If....'?

2021-01-04 18:03 UTC, cda69 reviewed
Just the one comment about whether the 'If' should read 'In', otherwise, all good.

2021-01-05 10:08 UTC, cda69 approved these changes

2021-01-05 12:57 UTC, cda69 approved these changes

2021-01-05 16:10 UTC, davidaruddy requested changes
On _pages/functional_spec/error/er_errorhandling.md, I have noticed some issues that pre-date your changes! Now I have seen them I cannot un-see them lol Would you mind adding the changes into this update?

- Could we remove the reference to "FoT" as I think we have now moved beyond that
- Here: under responses(https://rw-dev-branch.uec-appts.docs.opennhs.io/er_errorhandling.html) there is a typo on the word Scheduling could you fix it (again, not your typo but now I see it.....)

2021-01-05 16:12 UTC, davidaruddy approved these changes

2021-01-14 14:21 UTC, merged