TKW Simulators - Install and Use
nhsd-a2si/docs-uec-appts pull request #375
Opened 2021-01-26 17:27 UTC by cda69

Covering overview of TKW Simulators - installation and their functionality - all under this page https://cd-dev-branch.uec-appts.docs.opennhs.io/sims_install.html (might need to split but see what you think)

2021-01-27 11:13 UTC, RichardTheWard approved these changes
Collapsable sections make navigation easy, so no need to split

2021-02-04 12:38 UTC, RichardTheWard approved these changes

2021-02-04 14:04 UTC, davidaruddy requested changes
Could you remove the reference to the "old demonstrator" and then move the TKW page (if only a single page is left) into the main "overview toolbar" as the separate section (with its own toolbar) is now no longer required?

Otherwise all excellent work!

2021-02-04 14:05 UTC, davidaruddy approved these changes

2021-02-04 18:07 UTC, merged